OCOP/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'OCOP'

urlpatterns = [
    path('',views.main_page,name='OCOP'),
    path('login/',auth_views.LoginView.as_view(template_name='OCOP/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.signup,name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from OCOP import views

urlpatterns = [
    path('OCOP/',include('OCOP.urls')),
    path('admin/', admin.site.urls),
    path('point/', include('point.urls')),
    path('mypage/', include('mypage.urls')),
    path('pybo/', include('pybo.urls')),
    path('',views.main_page,name='index')
]

point/urls.py
from django.urls import path
from . import views

app_name = "point"

urlpatterns = [
    path('createcarbon/', views.Createcarbon, name='createcarbon'),
    path('creategreen/', views.Creategreen, name='creategreen'),
    path('carbonlist/', views.Carbonlist, name='carbonlist'),
    path('greenlist/', views.Greenlist, name='greenlist'),
    path('carbonlist/modify/<int:Carbonpoint_id>/', views.Carbon_Modify, name='carbonmodify'),
    path('greenlist/modify/<int:Greenpoint_id>/', views.Green_Modify, name='greenmodify'),
    path('carbonlist/delete/<int:Carbonpoint_id>/', views.Carbon_Delete, name='carbondelete'),
    path('greenlist/delete/<int:Greenpoint_id>/', views.Green_Delete, name='greendelete'),
    path('carbon/', views.Carbonpage, name='carbonpage'),
    path('green/', views.Greenpage, name='greenpage'),
]

point/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.

class Carbonpoint(models.Model):
    pointtype = models.TextField()
    cpoint = models.IntegerField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'carbonlist'
        verbose_name = '탄소포인트목록'
    def __str__(self):
        return self.pointtype

class Greenpoint(models.Model):
    pointtype = models.TextField()
    gpoint = models.IntegerField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'greenlist'
        verbose_name = '그린포인트목록'
    def __str__(self):
        return self.pointtype

class Carbon(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    point = models.ForeignKey(Carbonpoint, on_delete=models.CASCADE)
    # practice =
    # container =
    # refill =
    # total =
    active = models.BooleanField(default = True)
    quantity = models.PositiveSmallIntegerField(null=True, default=0, validators=[MinValueValidator(1), MaxValueValidator(100)])
    create_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'carbonuser'
        verbose_name = '탄소포인트'

# class Green(models.Model):
#     user =
#     saving =
#     hiking =
#     greenpoint =
#     create_date = models.DateTimeField(auto_now_add=True)
#
# class Vehicle(models.Model):
#     user =
#     stdmileage =
#     confmileage =
#     rdtmileage =
#     rdtrate =
#     create_date = models.DateTimeField(auto_now_add=True)

point/forms.py
from django import forms
from point.models import Carbonpoint, Greenpoint

class CarbonForm(forms.ModelForm):
    class Meta:
        model = Carbonpoint
        fields = ['pointtype', 'cpoint']

        labels = {
            'pointtype':'포인트 종류',
            'cpoint':'포인트량',
        }


class GreenForm(forms.ModelForm):
    class Meta:
        model = Greenpoint
        fields = ['pointtype', 'gpoint']

        labels = {
            'pointtype': '포인트 종류',
            'gpoint': '포인트량',
        }

point/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Carbonpoint, Greenpoint, Carbon
from .forms import CarbonForm, GreenForm
from django.utils import timezone
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.


def Createcarbon(request):
    """
    admin계정만 들어와서 포인트 종류 입력 가능
    """
    if request.method == 'POST':
        form = CarbonForm(request.POST)
        if form.is_valid():
            carbonpoint = form.save(commit=False)
            carbonpoint.create_date = timezone.now()
            carbonpoint.save()
            return redirect('point:carbonlist')
    else:
        form = CarbonForm()

    context = {'form': form}
    return render(request, 'point/carbonform.html', context)

def Creategreen(request):
    """
    admin계정만 들어와서 포인트 종류 입력 가능
    """
    if request.method == 'POST':
        form = GreenForm(request.POST)
        if form.is_valid():
            greenpoint = form.save(commit=False)
            greenpoint.create_date = timezone.now()
            greenpoint.save()
            return redirect('point:greenlist')
    else:
        form = GreenForm()

    context = {'form': form}
    return render(request, 'point/greenform.html', context)

def Carbonlist(request):
    """
    탄소포인트, 그린포인트 목록을 보여주고 수정 추가 삭제 가능
    """
    carbonlist = Carbonpoint.objects.order_by('create_date')
    context = {'carbonlist': carbonlist}
    return render(request, 'point/carbonlist.html', context)

def Greenlist(request):
    """
    탄소포인트, 그린포인트 목록을 보여주고 수정 추가 삭제 가능
    """
    greenlist = Greenpoint.objects.order_by('create_date')
    context = {'greenlist': greenlist}
    return render(request, 'point/greenlist.html', context)

def Carbon_Modify(request, Carbonpoint_id):
    """
    admin계정만 들어와서 포인트 수정 가능
    """
    carbon = get_object_or_404(Carbonpoint, pk=Carbonpoint_id)

    if request.method == 'POST':
        form = CarbonForm(request.POST, instance = carbon)
        if form.is_valid():
            carbonpoint = form.save(commit=False)
            carbonpoint.modify_date = timezone.now()
            carbonpoint.save()
            return redirect('point:carbonlist')
    else:
        form = CarbonForm(instance=carbon)

    context = {'form': form}
    return render(request, 'point/carbonmodify.html', context)

def Green_Modify(request, Greenpoint_id):
    """
    admin계정만 들어와서 포인트 수정 가능
    """
    green = get_object_or_404(Greenpoint, pk=Greenpoint_id)

    if request.method == 'POST':
        form = GreenForm(request.POST, instance = green)
        if form.is_valid():
            greenpoint = form.save(commit=False)
            greenpoint.modify_date = timezone.now()
            greenpoint.save()
            return redirect('point:greenlist')
    else:
        form = GreenForm(instance=green)

    context = {'form': form}
    return render(request, 'point/greenmodify.html', context)

def Carbon_Delete(request, Carbonpoint_id):
    """
    탄소포인트 삭제
    """
    carbon = get_object_or_404(Carbonpoint, pk = Carbonpoint_id)

    carbon.delete()
    return redirect('point:carbonlist')

def Green_Delete(request, Greenpoint_id):
    """
    그린포인트 삭제
    """
    green = get_object_or_404(Greenpoint, pk = Greenpoint_id)

    green.delete()
    return redirect('point:greenlist')




def Carbonpage(request):
    """
    탄소페이지 보여줌
    """
    carbon_list = Carbonpoint.objects.order_by('create_date')
    context = {'carbon_list': carbon_list}
    return render(request, 'point/carbon.html', context)

def Greenpage(request):
    """
    그린페이지 보여줌
    """
    green_list = Greenpoint.objects.order_by('create_date')
    context = {'green_list': green_list}
    return render(request, 'point/green.html', context)




#
# def add_carbon(request):
#     selpoint = Carbonpoint.objects.get(id=Carbonpoint.id)
#
#     try:
#
# def my_carbon():

templates/point/carbon.html
{% extends 'base.html' %}

{% block content %}

<div>
    <div class="green-title">
            <h5 class="my-3 border-bottom pb-2" align="center">탄소포인트</h5>
    </div>
    <div>
        <div class="green-list">
            {% for Carbonpoint in carbon_list %}
            <input type="checkbox">{{ Carbonpoint.pointtype }}</input>
            <td>{{ Carbonpoint.cpoint }}P</td>
            <p></p>
            {% endfor %}
            <button type="" class="btn btn-primary">조회하기</button>
        </div>
        <div>

        </div>
        <div>
            <button type="submit" class="btn btn-primary">삭제하기</button>
            <button type="submit" class="btn btn-primary">계산하기</button>
        </div>
    </div>
</div>
{% endblock %}

templates/point/carbonform.html
{% extends 'base.html' %}

{% block content %}
<div>
    <h5 >탄소포인트</h5>
    <form method = "post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type = 'submit' class = 'btn btn-primary'>저장하기</button>
    </form>
</div>
{% endblock %}

templates/point/carbonlist.html
{% extends 'base.html' %}

{% block content %}

<div>
    <div class="green-title">
            <h5 class="my-3 border-bottom pb-2" align="center">탄소포인트</h5>
    </div>
    <div>

        <div class="carbon-list">
            {% csrf_token %}
            {% for Carbonpoint in carbonlist %}
            <td>{{ Carbonpoint.pointtype }}</td>
            <td>{{ Carbonpoint.cpoint }}P</td>
            <td>{{ Carbonpoint.create_date }}</td>
            <td>{{ Carbonpoint.modify_date }}</td>
            <a href = "{% url 'point:carbonmodify' Carbonpoint.id %}" class = 'btn btn-sm btn-outline-secondary'>수정하기</a>
            <a href = "#" class = 'delete btn btn-sm btn-outline-secondary' data-uri="{% url 'point:carbondelete' Carbonpoint.id %}">삭제하기</a>
            <p></p>
            {% endfor %}
        </div>

    </div>
        <div>
            <a href="{% url 'point:createcarbon' %}" class="btn btn-primary">추가하기</a>
        </div>
</div>
{% endblock %}

{% block script %}
<script type = 'text/javascript'>
    $(document).ready(function(){
        $(".delete").on('click', function(){
            if(confirm('정말로 삭제하시겠습니까?')){
                location.href = $(this).data('uri');
            }
        });
    });
</script>
{% endblock %}

templates/point/carbonmodify.html
{% extends 'base.html' %}

{% block content %}
<div>
    <h5 >탄소포인트</h5>
    <form method = "post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type = 'submit' class = 'btn btn-primary'>저장하기</button>
    </form>
</div>
{% endblock %}

templates/point/green.html
{% extends 'base.html' %}

{% block content %}

<div>
    <div class="green-title">
            <h5 class="my-3 border-bottom pb-2" align="center">그린포인트</h5>
    </div>
    <div>
        <div class="green-list">
            {% for Greenpoint in green_list %}
            <input type="checkbox">{{ Greenpoint.pointtype }}</input>
            <td>{{ Greenpoint.gpoint }}P</td>
            <p></p>
            {% endfor %}
            <button type="" class="btn btn-primary">조회하기</button>
        </div>
        <div>

            <textarea  class = 'form-control' name = 'content' id = 'content'
                       rows = '10'>{{ form.content.value|default_if_none:'' }}</textarea>

            <button type="submit" class="btn btn-primary">삭제하기</button>
            <button type="submit" class="btn btn-primary">계산하기</button>
        </div>
    </div>
</div>
{% endblock %}

templates/point/greenform.html
{% extends 'base.html' %}

{% block content %}
<div>
    <h5 >그린포인트</h5>
    <form method = "post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type = 'submit' class = "btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/point/greenlist.html
{% extends 'base.html' %}

{% block content %}

<div>
    <div class="green-title">
            <h5 class="my-3 border-bottom pb-2" align="center">그린포인트</h5>
    </div>
    <div>
        <div class="green-list">
            {% csrf_token %}
            {% for Greenpoint in greenlist %}
            <td>{{ Greenpoint.pointtype }}</td>
            <td>{{ Greenpoint.gpoint }}P</td>
            <td>{{ Greenpoint.create_date }}</td>
            <td>{{ Greenpoint.modify_date }}P</td>
            <a href = "{% url 'point:greenmodify' Greenpoint.id %}" class = 'btn btn-sm btn-outline-secondary'>수정하기</a>
            <a href = "#" class = 'delete btn btn-sm btn-outline-secondary' data-uri="{% url 'point:greendelete' Greenpoint.id %}">삭제하기</a>
            <p></p>
            {% endfor %}

        </div>
    </div>
        <div>
            <a href="{% url 'point:creategreen' %}" class="btn btn-primary">추가하기</a>
        </div>
</div>
{% endblock %}

{% block script %}
<script type = 'text/javascript'>
    $(document).ready(function(){
        $(".delete").on('click', function(){
            if(confirm('정말로 삭제하시겠습니까?')){
                location.href = $(this).data('uri');
            }
        });
    });
</script>
{% endblock %}

templates/point/greenmodify.html
{% extends 'base.html' %}

{% block content %}
<div>
    <h5 >그린포인트</h5>
    <form method = "post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type = 'submit' class = 'btn btn-primary'>저장하기</button>
    </form>
</div>
{% endblock %}