OCOP/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'OCOP'

urlpatterns = [
    path('',views.main_page,name='OCOP'),
    path('login/',auth_views.LoginView.as_view(template_name='OCOP/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.signup,name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from OCOP import views

urlpatterns = [
    path('OCOP/',include('OCOP.urls')),
    path('admin/', admin.site.urls),
    path('point/', include('point.urls')),
    path('mypage/', include('mypage.urls')),
    path('pybo/', include('pybo.urls')),
    path('',views.main_page,name='index')
]

pybo/urls.py
from django.urls import path

from . import views

app_name = 'pybo'

urlpatterns = [
    path('', views.pybo, name='pybo'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('question/create/', views.question_create, name = 'question_create'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),

    #수정
    path('question/modify/<int:question_id>', views.question_modify, name='question_modify'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),

    #삭제
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),

    # 추천
    path('vote/question/<int:question_id>/', views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', views.vote_answer, name='vote_answer'),

    #category
    path('question/list/', views.pybo, name='pybo'),
    path('question/list/<str:category_name>/', views.pybo, name='pybo'),
    path('question/detail/<int:question_id>/', views.detail, name='detail'),
    path('question/create/<str:category_name>/', views.question_create, name='question_create'),
]

pybo/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=20, unique=True)
    description = models.CharField(max_length=200, null=True, blank=True)
    has_answer = models.BooleanField(default=True)  # 답변가능 여부

    class Meta:
        db_table = 'pybo_category'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('pybo:pybo', args=[self.name])

class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, blank=True, related_name='voter_question')  # 추천인 추가
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category_question')

    class Meta:
        ordering = ['id']

    def __str__(self):
        return self.subject # id 값 대신 제목 표시

    def get_absolute_url(self):
        return reverse('pybo:question_detail', args=[self.id])

    def get_recent_comments(self):
        return self.comment_set.all().order_by('-create_date')[:5]

class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='category_answer')  # 추천인 추가

pybo/forms.py
from django import forms
from pybo.models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta: #모델 폼은 이너 클래스인 Meta 클래스가 반드시 필요하다. Meta 클래스에는 사용할 모델과 모델의 속성을 적어야 한다.
        model = Question  # 사용할 모델
        fields = ['subject', 'content']  # QuestionForm에서 사용할 Question 모델의 속성
        labels = {
            'subject': '제목',
            'content': '내용',
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

pybo/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Question, Answer, Category
from .forms import QuestionForm, AnswerForm
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.db.models import Q, Count
# from django.http import HttpResponse

# Create your views here.
def pybo(request, category_name='notice'):
    """
    pybo 목록 출력
    """
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    so = request.GET.get('so', 'recent')  # 정렬기준

    category_list = Category.objects.all()
    category = get_object_or_404(Category, name=category_name)
    question_list = Question.objects.filter(category=category)
    question_all_list = Question.objects.all()

    # 정렬
    if so == 'recommend':
        question_list = question_list.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        question_list = question_list.annotate(num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else:  # recent
        question_list = question_list.order_by('-create_date')

    # 조회, 검색
    # question_list = Question.objects.order_by('-create_date')
    if kw:
        question_list = question_all_list.filter(
            Q(subject__icontains=kw) |  # 제목검색
            Q(content__icontains=kw) #|  # 내용검색
            # Q(author__username__icontains=kw) |  # 질문 글쓴이검색
            # Q(answer__author__username__icontains=kw)  # 답변 글쓴이검색
        ).distinct()

    # 페이징처리
    paginator = Paginator(question_list, 5)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {'question_list': page_obj, 'page': page, 'kw': kw, 'so': so,
               'category_list': category_list, 'category': category}
    return render(request, 'pybo/question_list.html', context)

def detail(request, question_id):
    """
    pybo 내용 출력
    """
    question = get_object_or_404(Question, pk=question_id) # pk = primary key
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

@login_required(login_url='common:login')
def question_create(request, category_name):
    """
    pybo 질문등록
    """
    category = Category.objects.get(name=category_name)

    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user  # author 속성에 로그인 계정 저장
            question.create_date = timezone.now()
            question.category = category
            question.save()
            return redirect(category)
    else: # request.method == 'GET'
        form = QuestionForm()
    context = {'form': form, 'category':category }
    return render(request, 'pybo/question_form.html', context)

@login_required(login_url='common:login')
def question_modify(request, question_id):
    """
    pybo 질문수정
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('pybo:detail', question_id=question.id)

    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user  # author 속성에 로그인 계정 저장
            question.modify_date = timezone.now()  # 수정일시 저장
            question.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

@login_required(login_url='common:login')
def question_delete(request, question_id):
    """
    pybo 질문삭제
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('pybo:detail', question_id=question.id)
    question.delete()
    return redirect('pybo:index')

@login_required(login_url='common:login')
def answer_create(request, question_id):
    """
    pybo 답변등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user  # author 속성에 로그인 계정 저장
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)

@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    """
    pybo 답변수정
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('pybo:detail', question_id=answer.question.id)

    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('pybo:detail', question_id=answer.question.id)
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'pybo/answer_form.html', context)

@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    """
    pybo 답변삭제
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        answer.delete()
    return redirect('pybo:detail', question_id=answer.question.id)

def vote_question(request, question_id):
    """
    pybo 질문추천등록
    """
    question = get_object_or_404(Question, pk=question_id)
    # if request.user == question.author:
    #     messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    # else:
    question.voter.add(request.user)
    return redirect('pybo:detail', question_id=question.id)

@login_required(login_url='common:login')
def vote_answer(request, answer_id):
    """
    pybo 답글추천등록
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    # if request.user == answer.author:
    #     messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    # else:
    answer.voter.add(request.user)
    return redirect('pybo:detail', question_id=answer.question.id)

templates/pybo/answer_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">답변내용</label>
            <textarea class="form-control" name="content" id="content" 
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/question_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <!-- 사용자오류 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="row my-3">
        <div class="col-1"> <!-- 추천영역 -->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{question.voter.count}}</div>
            <a href="#" data-uri="{% url 'pybo:vote_question' question.id  %}"
               class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>
        <div class="col-11"> <!-- 질문영역 -->
        <!-- 기존내용 -->
            <div class="card">
                <div class="card-body">
                    <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
                    <div class="d-flex justify-content-end">
                        {% if question.modify_date %}
                        <div class="badge badge-light p-2 text-left mx-3">
                            <div class="mb-2">수정일자</div>
                            <div>{{ question.modify_date }}</div>
                        </div>
                        {% endif %}
                        <div class="badge badge-light p-2 text-left">
                            <div class="mb-2">{{ question.author.username }}</div>
                            <div>{{ question.create_date }}</div>
                        </div>
                    </div>
                    {% if request.user == question.author %}
                        <div class="my-3">
                            <a href="{% url 'pybo:question_modify' question.id  %}"
                               class="btn btn-sm btn-outline-secondary">수정</a>
                            <a href="#" class="delete btn btn-sm btn-outline-secondary"
                                data-uri="{% url 'pybo:question_delete' question.id  %}">삭제</a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="row my-3">
    <div class="col-1">  <!-- 추천영역 -->
        <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{answer.voter.count}}</div>
        <a href="#" data-uri="{% url 'pybo:vote_answer' answer.id  %}"
            class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
    </div>
    <div class="col-11">  <!-- 답변영역 -->
        <div class="card">
            <div class="card-body">
                <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
                <div class="d-flex justify-content-end">
                    {% if answer.modify_date %}
                    <div class="badge badge-light p-2 text-left mx-3">
                        <div class="mb-2">수정일자</div>
                        <div>{{ answer.modify_date }}</div>
                    </div>
                    {% endif %}
                    <div class="badge badge-light p-2 text-left">
                        <div class="mb-2">{{ answer.author.username }}</div>
                        <div>{{ answer.create_date }}</div>
                    </div>
                </div>
                {% if request.user == answer.author %}
                    <div class="my-3">
                        <a href="{% url 'pybo:answer_modify' answer.id  %}"
                           class="btn btn-sm btn-outline-secondary">수정</a>
                        <a href="#" class="delete btn btn-sm btn-outline-secondary "
                            data-uri="{% url 'pybo:answer_delete' answer.id  %}">삭제</a>
                    </div>
                {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}<!--form 태그 바로 밑에 {% csrf_token %} 태그를 항상 위치-->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
        {% endfor %}
        </div>
        {% endif %}
        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}
{% block script %}
<!--삭제버튼 확인창-->
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>

<!--추천버튼 확인창-->
<script type='text/javascript'>
$(document).ready(function(){
    $(".recommend").on('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>
{% endblock %}

templates/pybo/question_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">[{{ category.description }}]질문등록</h5>
    <form method="post" class="post-form my-3"> <!--form 태그에 action 속성을 지정하지 않으면 현재 페이지의 URL이 디폴트 action으로 설정-->
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/question_list.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
<div class="container my-3">
    <div class = "row">
         <div class="col-sm-12 col-md-3 col-lg-2 p-2" style ="font-size:14px;">
            <!-- Sidebar  -->
            <nav id="sidebar" class="border-top border-secondary">
                <div class="list-group">
                    {% for cat in category_list %}
                        {% if cat == category %}
                            <a class="rounded-0 list-group-item list-group-item-action list-group-item-light active"
                               href="{{ cat.get_absolute_url }}">{{ cat.description }}</a>
                        {% else %}
                            <a class="rounded-0 list-group-item list-group-item-action list-group-item-light"
                               href="{{ cat.get_absolute_url }}">{ cat.description }}</a>
                        {% endif %}
                    {% endfor %}
                </div>
            </nav>
         </div>

        <div class="col-sm-12 col-md-9 col-lg-9 p-2">
            <!-- Content -->
            <div id="content" class="border-top border-secondary">
                <div class="content_block">
                <h5 class="border-bottom pl-2 pb-3 my-2">{{ category.description }}</h5>
                    <div class="row justify-content-between my-3">  <!-- 양쪽정렬 justify-content-between로 변경 -->
                        <div class="col-2">
                            <select class="form-control so">
                                <option value="recent" {% if so == 'recent' %}selected{% endif %}>최신순</option>
                                <option value="recommend" {% if so == 'recommend' %}selected{% endif %}>추천순</option>
                                <option value="popular" {% if so == 'popular' %}selected{% endif %}>인기순</option>
                            </select>
                        </div>
                        <div class="col-4 input-group">
                            <input type="text" class="form-control kw" value="{{ kw|default_if_none:'' }}">
                            <div class="input-group-append">
                                <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                            </div>
                        </div>
                    </div>

                    <table class="table">
                        <thead>
                        <tr class="text-center thead-dark">
                            <th>번호</th>
                            <th>추천</th>
                            <th style = "width: 50%">제목</th>
                            <th>글쓴이</th>
                            <th>작성일시</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% if question_list %}
                        {% for question in question_list %}
                        <tr class="text-center">
                            <td>
                                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                                {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
                            </td>
                             <td>
                                {% if question.voter.all.count > 0 %}
                                    {{ question.voter.all.count }}
                                {% endif %}
                            </td>
                            <td class="text-center">
                                <a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a>
                                <!--답변 개수-->
                                {% if question.answer_set.count > 0 %}
                                <span class="text-danger small ml-2">{{ question.answer_set.count }}</span>
                                {% endif %}
                            </td>
                            <td>{{ question.author.username }}</td> <!--글쓴이 추가-->
                            <td>{{ question.create_date }}</td>
                        </tr>
                        {% endfor %}
                        {% else %}
                        <tr>
                            <td colspan="3">질문이 없습니다.</td>
                        </tr>
                        {% endif %}
                        </tbody>
                    </table>
                    <a href="{% url 'pybo:question_create' category.name %}" class="btn btn-primary">질문 등록하기</a>
                </div>
            </div>
        </div>

    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.previous_page_number }}" href="#">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in question_list.paginator.page_range %}
            {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %} <!--페이지 표시 제한 기능-->
                {% if page_number == question_list.number %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
                </li>
                {% endif %}
             {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
            <li class="page-item">
                <a class="page-link" data-page="{{ question_list.next_page_number }}" href="#">다음</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
            </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    </div>
</div>
<form id="searchForm" method="get" action="{% url 'pybo:pybo' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
    <input type="hidden" id="so" name="so" value="{{ so }}">
</form>
{% endblock %}

{% block script %}

<!--검색버튼을 클릭할 경우 1페이지부터 조회한다.-->
<script type='text/javascript'>
$(document).ready(function(){
    $(".page-link").on('click', function() {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });

    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);
        $("#searchForm").submit();
    });
});
</script>

<!--정렬 기준(select)을 변경할 때 searchForm 요청이 발생-->
<script type='text/javascript'>
$(document).ready(function(){
    $(".so").on('change', function() {
        $("#so").val($(this).val());
        $("#page").val(1);
        $("#searchForm").submit();
    });
});
</script>

{% endblock %}