OCOP/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'OCOP'

urlpatterns = [
    path('',views.main_page,name='OCOP'),
    path('login/',auth_views.LoginView.as_view(template_name='OCOP/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.signup,name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from OCOP import views

urlpatterns = [
    path('OCOP/',include('OCOP.urls')),
    path('admin/', admin.site.urls),
    path('point/', include('point.urls')),
    path('mypage/', include('mypage.urls')),
    path('pybo/', include('pybo.urls')),
    path('',views.main_page,name='index')
]

mypage/urls.py
from django.urls import path

from . import views

app_name = 'mypage'

urlpatterns = [
    path('', views.mypage, name='mypage'),
]

point/urls.py
from django.urls import path
from . import views

app_name = "point"

urlpatterns = [
    path('createcarbon/', views.Createcarbon, name='createcarbon'),
    path('creategreen/', views.Creategreen, name='creategreen'),
    path('carbonlist/', views.Carbonlist, name='carbonlist'),
    path('greenlist/', views.Greenlist, name='greenlist'),
    path('carbonlist/modify/<int:Carbonpoint_id>/', views.Carbon_Modify, name='carbonmodify'),
    path('greenlist/modify/<int:Greenpoint_id>/', views.Green_Modify, name='greenmodify'),
    path('carbonlist/delete/<int:Carbonpoint_id>/', views.Carbon_Delete, name='carbondelete'),
    path('greenlist/delete/<int:Greenpoint_id>/', views.Green_Delete, name='greendelete'),
    path('carbon/', views.Carbonpage, name='carbonpage'),
    path('green/', views.Greenpage, name='greenpage'),
]

pybo/urls.py
from django.urls import path

from . import views

app_name = 'pybo'

urlpatterns = [
    path('', views.pybo, name='pybo'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('question/create/', views.question_create, name = 'question_create'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),

    #수정
    path('question/modify/<int:question_id>', views.question_modify, name='question_modify'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),

    #삭제
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),

    # 추천
    path('vote/question/<int:question_id>/', views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', views.vote_answer, name='vote_answer'),

    #category
    path('question/list/', views.pybo, name='pybo'),
    path('question/list/<str:category_name>/', views.pybo, name='pybo'),
    path('question/detail/<int:question_id>/', views.detail, name='detail'),
    path('question/create/<str:category_name>/', views.question_create, name='question_create'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>OCO:P</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href='{% static "assets/logo.JPG" %}' />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href='{% static "css/styles.css" %}' rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-success">
            <div class="container px-5">
                <img src='{% static "assets/navbar_logo.png" %}' width="30" height="30" alt="" >
                <a class="navbar-brand mb-0 h1" href="{% url 'OCOP:OCOP' %}"><strong>OCOP</strong></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="#">{{ user.get_username }}님</a></li>
                        <li class = "nav-item"><a class = "nav-link" href = "{% url 'OCOP:logout' %}">로그아웃</a></li>
                        <li class = "nav-item"><a class = "nav-link" href = "{% url 'point:carbonpage' %}">탄소포인트</a></li>
                        <li class = "nav-item"><a class = "nav-link" href = "{% url 'point:greenpage' %}">그린포인트</a></li>
                        <li class = "nav-item"><a class = "nav-link" href = "#">자동차탄소포인트</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'mypage:mypage' %}">마이페이지</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'pybo:pybo' %}">게시판</a></li>
                        {% else %}
                        <li class = "nav-item"><a class = "nav-link" href = "{% url 'OCOP:login' %}">로그인</a></li>
                        <li class = "nav-item"><a class = "nav-link" href = "{% url 'OCOP:signup' %}"><strong>회원가입</strong></a></li>
                        <li class = "nav-item"><a class = "nav-link" href = "{% url 'point:carbonpage' %}">탄소포인트</a></li>
                        <li class = "nav-item"><a class = "nav-link" href = "{% url 'point:greenpage' %}">그린포인트</a></li>
                        <li class = "nav-item"><a class = "nav-link" href = "#">자동차탄소포인트</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'pybo:pybo' %}">게시판</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src='{% static "js/scripts.js" %}'></script>
        <!--jQuery JS-->
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %}
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->

    <!--자바스크립트 start-->
    {% block script %}
    {% endblock %}
    <!--자바스크립트 end-->

    </body>
</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %} <!--필드오류를 출력한다.-->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %} <!--넌필드오류를 출력한다.-->
        <div class="alert alert-danger">
            <strong>{{ errror }}</strong>
        </div>
    {% endfor %}
{% endif %}